# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dp_matrix_Rcpp <- function(data, beta, S = 10L, nb_initSpeed = 5L, data_var = 1.0) {
    .Call(`_splineOP_dp_matrix_Rcpp`, data, beta, S, nb_initSpeed, data_var)
}

#' Compute the sum of a numeric vector (C++ implementation)
#'
#' This function computes the sum of a numeric vector using a standard C++
#' vector structure. It provides performance comparable to the built-in
#' \code{sum()} function in R and serves as an example of integrating
#' native C++ code with R using Rcpp.
#'
#' @param v A numeric vector.
#'
#' @return A single numeric value: the sum of all elements in \code{v}.
#'
#' @examples
#' x <- runif(10)
#' cpp_sum2(x)
#'
#' @export
cpp_sum2 <- function(v) {
    .Call(`_splineOP_cpp_sum2`, v)
}

