# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Square Each Element of a States Matrix
#'
#' @description
#' Given a matrix of states of size S x N, this function returns a new matrix
#' where each element is squared. Additional arguments `data` and `beta` are
#' included for future extensions but are not used in the squaring.
#'
#' @param data Numeric vector of length N (currently unused).
#' @param beta Numeric penalty value (currently unused).
#' @param states Numeric matrix of size S x N.
#'
#' @return Numeric matrix of size S x N where each element is squared.
#'
#' @examples
#' library(Rcpp)
#' # Create example states matrix
#' states <- matrix(1:6, nrow = 2, ncol = 3)
#' data <- c(10, 20, 30)
#' beta <- 0.5
#' # Call the function
#' square_states(data, beta, states)
#'
#' @export
square_states <- function(data, beta, states) {
    .Call(`_splineOP_square_states`, data, beta, states)
}

#' Compute the sum of a numeric vector (C++ implementation)
#'
#' This function computes the sum of a numeric vector using a standard C++
#' vector structure. It provides performance comparable to the built-in
#' \code{sum()} function in R and serves as an example of integrating
#' native C++ code with R using Rcpp.
#'
#' @param v A numeric vector.
#'
#' @return A single numeric value: the sum of all elements in \code{v}.
#'
#' @examples
#' x <- runif(10)
#' cpp_sum2(x)
#'
#' @export
cpp_sum2 <- function(v) {
    .Call(`_splineOP_cpp_sum2`, v)
}

